name: CI

on:
  push:
  pull_request:

jobs:
  python:
    name: Python (lint & test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: py
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest black ruff

      - name: Lint (ruff) & Format check (black)
        run: |
          ruff check src tests
          black --check src tests

      - name: Run tests (pytest)
        env:
          PLAYGROUND_ROOT: ${{ github.workspace }}
        run: pytest -q

      - name: Upload Python results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: py-results
          path: ../data/results/**/*
          if-no-files-found: ignore

  c:
    name: C (build & test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build (make)
        run: make -C c

      - name: Run C tests
        run: make -C c test

      - name: Upload C results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: c-results
          path: data/results/**/*
          if-no-files-found: ignore
