name: CI

on:
  push:
  pull_request:

jobs:
  python:
    name: Python (lint & test)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: py
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          pip install pytest black ruff

      - name: Lint (ruff) & Format check (black)
        run: |
          ruff check src tests
          black --check src tests

      - name: Run tests (pytest)
        env:
          PLAYGROUND_ROOT: ${{ github.workspace }}
        run: pytest -q

      - name: Upload Python results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: py-results
          path: ${{ github.workspace }}/data/results/**
          if-no-files-found: ignore

  c:
    name: C (build & test)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Show workspace (debug)
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
          pwd
          echo "== ls -la =="
          ls -la
          echo "== git ls-tree HEAD =="
          git ls-tree --name-only HEAD

      # ここで存在確認。なければ早期終了してログを見やすく
      - name: Ensure c/ exists
        run: |
          if [ ! -d "$GITHUB_WORKSPACE/c" ]; then
            echo "::error::c/ directory not found at $GITHUB_WORKSPACE"
            exit 1
          fi

      - name: Build (make)
        run: make -C c

      - name: Run C tests
        run: make -C c test

      - name: Upload C results (if any)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: c-results
          path: ${{ github.workspace }}/data/results/**
          if-no-files-found: ignore
