- name: Preflight: fingerprint API key (safe)
  env:
    OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
  run: |
    set -euo pipefail
    if [ -z "${OPENAI_API_KEY:-}" ]; then
      echo "::error::OPENAI_API_KEY is empty"; exit 1
    fi
    # 前後空白や CR を除去して整える（問題があれば警告）
    RAWLEN=${#OPENAI_API_KEY}
    CLEAN=$(printf "%s" "$OPENAI_API_KEY" | tr -d '\r' | sed -e 's/^ *//' -e 's/ *$//')
    CLEANLEN=${#CLEAN}
    if [ "$RAWLEN" -ne "$CLEANLEN" ]; then
      echo "::warning::OPENAI_API_KEY had surrounding spaces or CR; trimmed for use."
    fi
    echo -n "Key prefix: "; printf "%s" "$CLEAN" | cut -c1-10; echo "********"
    echo -n "Key sha256: "; printf "%s" "$CLEAN" | sha256sum | cut -c1-12
