name: Check OPENAI_API_KEY

on:
  workflow_dispatch:  # 手動実行できるようにする

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Show env (masked)
        run: |
          if [ -z "$OPENAI_API_KEY" ]; then
            echo "::error::OPENAI_API_KEY is empty"
            exit 1
          else
            echo "OPENAI_API_KEY is set (masked in logs)"
          fi

      - name: Call OpenAI API
        run: |
          curl -s -o result.json -w "%{http_code}\n" \
            https://api.openai.com/v1/models \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json"

          echo "Response status:"
          tail -n1 result.json
          echo "First part of JSON body:"
          head -c 200 result.json || true
